export const selectors = {
  headerTitle: '[data-test="header-title"]',
  searchInput: '[data-test="search-input"]',
  searchSubmitBtn: '[data-test="search-submit-btn"]',
  searchResultGrid: '[data-item-grid="search-result-grid"]',
  productName: (name) => `[data-item-name="${name}"]`,
  productId: (id) => `[data-item-id="${id}"]`,
  productTitle: '[data-test="product-title"]',
  addToCartBtn: '[data-test="add-to-cart-btn"]',
  cartCounter: '[data-test="cart-counter"]',
  cartViewFromAddCart: '[data-test="cart-view-from-add-cart-btn"]',
  cartItemName: (name) => `[data-cart-item-name="${name}"]`,
  cartItemId: (id) => `[data-cart-item-id="${id}"]`,
  cartItemQuantity:(quantity) => `input[data-cart-item-quantity="${quantity}"]`,
  cartSumaryPrice: '[data-test="cart-summary-price"]',
  cartRemoveItemBtn: '[data-test="remove-item-btn"]',
  emptyCartMessage: '[data-test="empty-cart-message"]',
  checkoutBtn: '[data-test="checkout-btn"]',
  checkoutName: '[data-test="checkout-name"]',
  checkoutAddress: '[data-test="checkout-address"]',
  checkoutEmail: '[checkout-payment-email]',
  checkoutCheckBoxPaymentMethod: '[type="checkbox"]',
  submitOrderBtn: '[data-test="submit-order-btn"]',
  orderConfirmationMessage: '[data-test="order-confirmation-message"]',
  thankYouMessage: '[data-test="thank-you-message"]',
  
};
